### ISSUE TITLE
执行脚本升级后无法使用

### ISSUE THREAD

**Issue by ccinoo** [wukongdaily/allinonescript#1]
悟空好，首先感谢您提供的一键脚本。但我执行后有报错，升级失败。以下是执行输出，能否帮忙看看？非常感谢。

`***********请确保软路由已处于科学上网状态***************

**************为安卓原生盒子设置主机名映射*****************

cfg06f37d

已添加新的域名记录

time.android.com    203.107.6.88 

**************安装关机等必备插件**********************************

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    57  100    57    0     0    676      0 --:--:-- --:--:-- --:--:--   750
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124  100   124    0     0   1691      0 --:--:-- --:--:-- --:--:--  1698
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    58  100    58    0     0    763      0 --:--:-- --:--:-- --:--:--   773
Downloading https://istore.linkease.com/repo/all/nas_luci/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_nas_luci
Downloading https://istore.linkease.com/repo/all/store/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_store
Downloading https://istore.linkease.com/repo/x86_64/nas/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_nas
Downloading https://istore.linkease.com/repo/all/compat/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/istore_compat
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/targets/x86/64/packages/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_core
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/base/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_base
Downloading https://mirrors.cloud.tencent.com/lede/releases/18.06.9/packages/x86_64/luci/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_luci
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/packages/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_packages
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/routing/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_routing
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_telephony
Downloading https://istore.linkease.com/repo/all/meta/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_meta
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Upgrading luci-lib-taskd on root from 1.0.17 to 1.0.18...
Downloading https://istore.linkease.com/repo/all/store/luci-lib-taskd_1.0.18_all.ipk
Configuring luci-lib-taskd.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Upgrading luci-app-store on root from 0.1.13-2 to 0.1.14-1...
Downloading https://istore.linkease.com/repo/all/store/luci-app-store_0.1.14-1_all.ipk
Configuring luci-app-store.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Installing app-meta-poweroff (1.0.0-1) to root...
Downloading https://istore.linkease.com/repo/all/meta/app-meta-poweroff_1.0.0-1_all.ipk
Configuring app-meta-poweroff.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Installing app-meta-ddnsto (3.0.4-1) to root...
Downloading https://istore.linkease.com/repo/all/meta/app-meta-ddnsto_3.0.4-1_all.ipk
Configuring app-meta-ddnsto.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Installing app-meta-systools (1.0.4-20230718) to root...
Downloading https://istore.linkease.com/repo/all/meta/app-meta-systools_1.0.4-20230718_all.ipk
Installing luci-lib-iform (1.1.1) to root...
Downloading https://istore.linkease.com/repo/all/nas_luci/luci-lib-iform_1.1.1_all.ipk
Installing speedtestcli (1.2.0-x86_64-1) to root...
Downloading https://istore.linkease.com/repo/x86_64/nas/speedtestcli_1.2.0-x86_64-1_all.ipk
Configuring luci-lib-iform.
Collected errors:
 * check_data_file_clashes: Package speedtestcli wants to install file /usr/bin/speedtest
        But that file is already provided by package  * luci-app-netspeedtest
 * opkg_install_cmd: Cannot install package app-meta-systools.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    57  100    57    0     0    678      0 --:--:-- --:--:-- --:--:--   678
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124  100   124    0     0   1626      0 --:--:-- --:--:-- --:--:--  1653
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    58  100    58    0     0    690      0 --:--:-- --:--:-- --:--:--   698
Downloading https://istore.linkease.com/repo/all/nas_luci/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_nas_luci
Downloading https://istore.linkease.com/repo/all/store/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_store
Downloading https://istore.linkease.com/repo/x86_64/nas/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_nas
Downloading https://istore.linkease.com/repo/all/compat/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/istore_compat
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/targets/x86/64/packages/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_core
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/base/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_base
Downloading https://mirrors.cloud.tencent.com/lede/releases/18.06.9/packages/x86_64/luci/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_luci
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/packages/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_packages
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/routing/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_routing
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_telephony
Downloading https://istore.linkease.com/repo/all/meta/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_meta
Installing app-meta-systools (1.0.4-20230718) to root...
Downloading https://istore.linkease.com/repo/all/meta/app-meta-systools_1.0.4-20230718_all.ipk
Installing speedtestcli (1.2.0-x86_64-1) to root...
Downloading https://istore.linkease.com/repo/x86_64/nas/speedtestcli_1.2.0-x86_64-1_all.ipk
Collected errors:
 * check_data_file_clashes: Package speedtestcli wants to install file /usr/bin/speedtest
        But that file is already provided by package  * luci-app-netspeedtest
 * opkg_install_cmd: Cannot install package app-meta-systools.
Installing app-meta-autotimeset (1.5-20220426) to root...
Downloading https://istore.linkease.com/repo/all/meta/app-meta-autotimeset_1.5-20220426_all.ipk
Installing luci-app-autotimeset (1.5-20220426) to root...
Downloading https://istore.linkease.com/repo/all/nas_luci/luci-app-autotimeset_1.5-20220426_all.ipk
Installing luci-i18n-autotimeset-zh-cn (git-22.116.29801-c9e327f) to root...
Downloading https://istore.linkease.com/repo/all/nas_luci/luci-i18n-autotimeset-zh-cn_git-22.116.29801-c9e327f_all.ipk
Configuring luci-app-autotimeset.
Configuring luci-i18n-autotimeset-zh-cn.
Configuring app-meta-autotimeset.

************正在下载三大插件*******************************

--2023-09-01 20:25:08--  https://raw.github.com/AUK9527/Are-u-ok/main/x86/all/OpenClash_x86_update.run
Resolving raw.github.com... 185.199.109.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.github.com|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/AUK9527/Are-u-ok/main/x86/all/OpenClash_x86_update.run [following]
--2023-09-01 20:25:09--  https://raw.githubusercontent.com/AUK9527/Are-u-ok/main/x86/all/OpenClash_x86_update.run
Resolving raw.githubusercontent.com... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6716862 (6.4M) [application/octet-stream]
Saving to: 'OpenClash_x86_update.run'

OpenClash_x86_update.run          100%[============================================================>]   6.41M   247KB/s    in 40s     

2023-09-01 20:25:49 (166 KB/s) - 'OpenClash_x86_update.run' saved [6716862/6716862]

--2023-09-01 20:25:49--  https://raw.github.com/AUK9527/Are-u-ok/main/x86/all/PassWall_x86_update.run
Resolving raw.github.com... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.github.com|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/AUK9527/Are-u-ok/main/x86/all/PassWall_x86_update.run [following]
--2023-09-01 20:25:49--  https://raw.githubusercontent.com/AUK9527/Are-u-ok/main/x86/all/PassWall_x86_update.run
Resolving raw.githubusercontent.com... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15192679 (14M) [application/octet-stream]
Saving to: 'PassWall_x86_update.run'

PassWall_x86_update.run           100%[============================================================>]  14.49M   686KB/s    in 37s     

2023-09-01 20:26:27 (398 KB/s) - 'PassWall_x86_update.run' saved [15192679/15192679]

--2023-09-01 20:26:27--  https://raw.github.com/AUK9527/Are-u-ok/main/x86/all/SSR-Plus_x86_update.run
Resolving raw.github.com... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.github.com|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/AUK9527/Are-u-ok/main/x86/all/SSR-Plus_x86_update.run [following]
--2023-09-01 20:26:28--  https://raw.githubusercontent.com/AUK9527/Are-u-ok/main/x86/all/SSR-Plus_x86_update.run
Resolving raw.githubusercontent.com... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13327835 (13M) [application/octet-stream]
Saving to: 'SSR-Plus_x86_update.run'

SSR-Plus_x86_update.run           100%[============================================================>]  12.71M  1.01MB/s    in 16s     

2023-09-01 20:26:45 (803 KB/s) - 'SSR-Plus_x86_update.run' saved [13327835/13327835]

***********正在安装三大插件*********************************

Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing OneClick install  100%  
Downloading https://istore.linkease.com/repo/all/compat/Packages.gz
Updated list of available packages in /var/opkg-lists/istore_compat
Downloading https://istore.linkease.com/repo/all/compat/Packages.sig
Signature check passed.
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/targets/x86/64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/targets/x86/64/packages/Packages.sig
Signature check failed.
Remove wrong Signature file.
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/base/Packages.sig
Signature check passed.
Downloading https://mirrors.cloud.tencent.com/lede/releases/18.06.9/packages/x86_64/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://mirrors.cloud.tencent.com/lede/releases/18.06.9/packages/x86_64/luci/Packages.sig
Signature check failed.
Remove wrong Signature file.
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/packages/Packages.sig
Signature check passed.
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/routing/Packages.sig
Signature check passed.
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/telephony/Packages.sig
Signature check passed.
Not downgrading package libcap-bin on root from 2.67-1 to 2.63-1.
Not downgrading package libcap on root from 2.67-1 to 2.63-1.
Installing libdb47 (4.7.25.4.NC-7) to root...
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/packages/libdb47_4.7.25.4.NC-7_x86_64.ipk
Installing libruby3.0 (3.0.3-2) to root...
Not downgrading package libxml2 on root from 2.10.3-2 to 2.9.12-1.
Package libyaml (0.2.5-1) installed in root is up to date.
Upgrading luci-app-openclash on root from 0.45.103-beta to 0.45.128-beta...
OpenClash Already Stop!
Removing obsolete file /usr/share/openclash/ui/yacd/assets/debounce.c2d20996.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/TextFitler.61537a57.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/chevron-down.dd238e96.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/roboto-mono-latin-400-normal.7295944e.woff2.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/useRemainingViewPortHeight.7395542b.js.
Removing obsolete file /usr/share/openclash/ui/dashboard/assets/vendor-076c6210.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Fab.a0a7e573.css.
Removing obsolete file /usr/share/openclash/ui/dashboard/assets/index-7e15a32d.css.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/index.8bb012c6.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Logs.4b8e75d1.css.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Select.6c389032.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/logs.43986220.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Connections.fb8ea59b.css.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Fab.ef67ff10.js.
Removing obsolete file /usr/share/openclash/ui/dashboard/assets/index-6ac9f125.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/inter-latin-800-normal.d08d7178.woff.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/index.92e2d967.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/inter-latin-400-normal.3ea830d4.woff.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/chart-lib.a8ad03fd.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Proxies.16b46af4.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/roboto-mono-latin-400-normal.dffdffa7.woff.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/index.esm.e4dd1508.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Logs.ac990610.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Select.1e55eba1.css.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Rules.e03c54a8.css.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/index.b38debfc.css.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Config.c09e8dbe.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/en.fb34eaf7.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Config.39d8d2ef.css.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/play.7b1a5f99.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/TextFitler.b21c0577.css.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/inter-latin-400-normal.0364d368.woff2.
Removing obsolete file /usr/share/openclash/ui/yacd/.nojekyll.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Proxies.3fa3509d.css.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/zh.9b79b7bf.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/inter-latin-800-normal.a51ac27d.woff2.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/index.171f553a.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Connections.e48eac36.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Rules.70e6962f.js.
Not downgrading package ruby-bigdecimal on root from 3.1.3-1 to 3.0.3-2.
Not downgrading package ruby-date on root from 3.1.3-1 to 3.0.3-2.
Installing ruby-dbm (3.0.3-2) to root...
Not downgrading package ruby-digest on root from 3.1.3-1 to 3.0.3-2.
Not downgrading package ruby-enc on root from 3.1.3-1 to 3.0.3-2.
Not downgrading package ruby-forwardable on root from 3.1.3-1 to 3.0.3-2.
Not downgrading package ruby-pstore on root from 3.1.3-1 to 3.0.3-2.
Not downgrading package ruby-psych on root from 3.1.3-1 to 3.0.3-2.
Not downgrading package ruby-stringio on root from 3.1.3-1 to 3.0.3-2.
Not downgrading package ruby-strscan on root from 3.1.3-1 to 3.0.3-2.
Not downgrading package ruby-yaml on root from 3.1.3-1 to 3.0.3-2.
Not downgrading package ruby on root from 3.1.3-1 to 3.0.3-2.
Configuring libdb47.
Configuring ruby-dbm.
Configuring luci-app-openclash.
cfg4e7882
Configuring libruby3.0.
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing OneClick install  100%  
Downloading https://istore.linkease.com/repo/all/compat/Packages.gz
Updated list of available packages in /var/opkg-lists/istore_compat
Downloading https://istore.linkease.com/repo/all/compat/Packages.sig
Signature check passed.
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/targets/x86/64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/targets/x86/64/packages/Packages.sig
Signature check failed.
Remove wrong Signature file.
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/base/Packages.sig
Signature check passed.
Downloading https://mirrors.cloud.tencent.com/lede/releases/18.06.9/packages/x86_64/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://mirrors.cloud.tencent.com/lede/releases/18.06.9/packages/x86_64/luci/Packages.sig
Signature check failed.
Remove wrong Signature file.
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/packages/Packages.sig
Signature check passed.
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/routing/Packages.sig
Signature check passed.
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/telephony/Packages.sig
Signature check passed.
Upgrading chinadns-ng on root from 2023.03.10-1 to 2023.05.08-1...
Package dns2socks (2.1-2) installed in root is up to date.
Package dns2tcp (1.1.0-1) installed in root is up to date.
Package haproxy (2.6.6-1) installed in root is up to date.
Not downgrading package ipt2socks on root from 1.1.3-3 to 1.1.3-2.
Not downgrading package libltdl7 on root from 2.4.7-1 to 2.4.6-2.
Not downgrading package liblua5.3-5.3 on root from 5.3.5-5 to 5.3.5-4.
Package libudns (0.4-1) installed in root is up to date.
Upgrading luci-app-passwall on root from 4.63-1 to 4.66-8...
Upgrading luci-i18n-passwall-zh-cn on root from 4.63-1 to 4.66-8...
Package microsocks (1.0.3-1) installed in root is up to date.
Upgrading naiveproxy on root from 111.0.5563.64-1-1 to 113.0.5672.62-1-1...
Package pdnsd-alt (1.2.9b-par-3) installed in root is up to date.
Package shadowsocks-libev-ss-local (3.3.5-1) installed in root is up to date.
Package shadowsocks-libev-ss-redir (3.3.5-1) installed in root is up to date.
Package shadowsocks-libev-ss-server (3.3.5-1) installed in root is up to date.
Package shadowsocksr-libev-ssr-check (2.5.6-9) installed in root is up to date.
Package shadowsocksr-libev-ssr-local (2.5.6-9) installed in root is up to date.
Package shadowsocksr-libev-ssr-redir (2.5.6-9) installed in root is up to date.
Package shadowsocksr-libev-ssr-server (2.5.6-9) installed in root is up to date.
Installing simple-obfs (0.0.5-1) to root...
Package tcping (0.3-1) installed in root is up to date.
Package unzip (6.0-8) installed in root is up to date.
Upgrading xray-core on root from 1.8.0-1 to 1.8.3-1...
Configuring chinadns-ng.
Configuring xray-core.
Configuring naiveproxy.
Configuring luci-app-passwall.
Collected errors:
 * opkg_conf_load: Could not lock /var/lock/opkg.lock: Resource temporarily unavailable.
Configuring luci-i18n-passwall-zh-cn.
Collected errors:
 * resolve_conffiles: Existing conffile /usr/share/passwall/rules/direct_host is different from the conffile in the new package. The new conffile will be placed at /usr/share/passwall/rules/direct_host-opkg.
 * resolve_conffiles: Existing conffile /usr/share/passwall/rules/proxy_host is different from the conffile in the new package. The new conffile will be placed at /usr/share/passwall/rules/proxy_host-opkg.
 * check_data_file_clashes: Package simple-obfs wants to install file /usr/bin/obfs-local
        But that file is already provided by package  * simple-obfs-client
 * opkg_install_cmd: Cannot install package simple-obfs.
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing OneClick install  100%  
Downloading https://istore.linkease.com/repo/all/compat/Packages.gz
*** Failed to download the package list from https://istore.linkease.com/repo/all/compat/Packages.gz

Downloading https://mirrors.cloud.tencent.com/lede/snapshots/targets/x86/64/packages/Packages.gz
*** Failed to download the package list from https://mirrors.cloud.tencent.com/lede/snapshots/targets/x86/64/packages/Packages.gz

Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/base/Packages.gz
*** Failed to download the package list from https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/base/Packages.gz

Downloading https://mirrors.cloud.tencent.com/lede/releases/18.06.9/packages/x86_64/luci/Packages.gz
*** Failed to download the package list from https://mirrors.cloud.tencent.com/lede/releases/18.06.9/packages/x86_64/luci/Packages.gz

Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/packages/Packages.gz
*** Failed to download the package list from https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/packages/Packages.gz

Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/routing/Packages.gz
*** Failed to download the package list from https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/routing/Packages.gz

Downloading https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/telephony/Packages.gz
*** Failed to download the package list from https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/telephony/Packages.gz

Collected errors:
 * opkg_download: Failed to download https://istore.linkease.com/repo/all/compat/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

 * opkg_download: Failed to download https://mirrors.cloud.tencent.com/lede/snapshots/targets/x86/64/packages/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

 * opkg_download: Failed to download https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/base/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

 * opkg_download: Failed to download https://mirrors.cloud.tencent.com/lede/releases/18.06.9/packages/x86_64/luci/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

 * opkg_download: Failed to download https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/packages/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

 * opkg_download: Failed to download https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/routing/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

 * opkg_download: Failed to download https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/telephony/Packages.gz, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

Package chinadns-ng (2023.05.08-1) installed in root is up to date.
Package dns2socks (2.1-2) installed in root is up to date.
Package dns2tcp (1.1.0-1) installed in root is up to date.
Not downgrading package ipt2socks on root from 1.1.3-3 to 1.1.3-2.
Package libudns (0.4-1) installed in root is up to date.
Package lua-neturl (1.1-1-3) installed in root is up to date.
Package luci-app-ssr-plus (187-1) installed in root is up to date.
Package luci-i18n-ssr-plus-zh-cn (187-1) installed in root is up to date.
Package microsocks (1.0.3-1) installed in root is up to date.
Package naiveproxy (113.0.5672.62-1-1) installed in root is up to date.
Package pdnsd-alt (1.2.9b-par-3) installed in root is up to date.
Package redsocks2 (0.67-4) installed in root is up to date.
Package shadowsocks-libev-ss-local (3.3.5-1) installed in root is up to date.
Package shadowsocks-libev-ss-redir (3.3.5-1) installed in root is up to date.
Package shadowsocks-libev-ss-server (3.3.5-1) installed in root is up to date.
Package shadowsocksr-libev-ssr-check (2.5.6-9) installed in root is up to date.
Package shadowsocksr-libev-ssr-local (2.5.6-9) installed in root is up to date.
Package shadowsocksr-libev-ssr-redir (2.5.6-9) installed in root is up to date.
Package shadowsocksr-libev-ssr-server (2.5.6-9) installed in root is up to date.
Installing simple-obfs (0.0.5-1) to root...
Package tcping (0.3-1) installed in root is up to date.
Package xray-core (1.8.3-1) installed in root is up to date.
Collected errors:
 * check_data_file_clashes: Package simple-obfs wants to install file /usr/bin/obfs-local
        But that file is already provided by package  * simple-obfs-client
 * opkg_install_cmd: Cannot install package simple-obfs.

**************为emotn store添加强制域名代理********************

keeflys.com  已添加到passwall代理域名
keeflys.com  已添加到SSRP强制域名代理

head: clash_last_version: No such file or directory
awk: clash_last_version: No such file or directory
***********正在安装clash dev内核*********************************

--2023-09-01 20:27:36--  https://raw.github.com/vernesong/OpenClash/core/master/dev/clash-linux-amd64.tar.gz
Resolving raw.github.com... failed: Try again.
wget: unable to resolve host address 'raw.github.com'
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now

tun内核的更新日期是：

***********正在安装clash tun内核*********************************

--2023-09-01 20:27:41--  https://raw.github.com/vernesong/OpenClash/core/master/premium/clash-linux-amd64-.gz
Resolving raw.github.com... failed: Try again.
wget: unable to resolve host address 'raw.github.com'
gzip: invalid magic
***********正在安装clash meta内核*********************************

--2023-09-01 20:27:46--  https://raw.github.com/vernesong/OpenClash/core/master/meta/clash-linux-amd64.tar.gz
Resolving raw.github.com... failed: Try again.
wget: unable to resolve host address 'raw.github.com'
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mv: can't rename '/etc/openclash/core/meta/clash': No such file or directory
***********正在升级Openclash客户端到最新版*************************

head: openclash_last_version: No such file or directory

OpenClash 发现新版本 : 

--2023-09-01 20:28:10--  https://raw.github.com/vernesong/OpenClash/package/master/luci-app-openclash__all.ipk
Resolving raw.github.com... failed: Try again.
wget: unable to resolve host address 'raw.github.com'
Collected errors:
 * pkg_init_from_file: Malformed package file newopenclash.ipk.

******************大功告成! 悟空all in one一键脚本全部安装完毕 *******************`

**Comment by wukongdaily** [comment]
你好，目前我还没有适配 非 iStoreOS系统，如果大家需要，后续会考虑的。其他固件和iStoreOS内核版本也是不同的，估计需要单独在调试。

**Comment by ccinoo** [comment]
原来如此，明白了，非常感谢。
