### ISSUE TITLE
执行一键安装脚本升级后无法使用

### ISSUE THREAD

**Issue by BGMISBPT** [wukongdaily/allinonescript#2]
悟空好，首先感谢您提供的一键脚本。但我执行后有异常。以下是执行输出，能否帮忙看看？非常感谢。

iStoreOS版本：istoreos-22.03.4-2023071416-x86-64-squashfs-combined-efi.img

硬件:J1900双千兆

异常情况：在iStoreOS终端执行命令后，系统没有变化，各种插件也没有加载出来。

***********请确保软路由已处于科学上网状态***************

**************为安卓原生盒子设置主机名映射*****************

相同的域名记录已存在，无需重复添加

time.android.com    203.107.6.88 

**************安装关机等必备插件**********************************

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    57  100    57    0     0    372      0 --:--:-- --:--:-- --:--:--   380
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124  100   124    0     0    791      0 --:--:-- --:--:-- --:--:--   805
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    58  100    58    0     0    388      0 --:--:-- --:--:-- --:--:--   397
Downloading https://istore.linkease.com/repo/all/nas_luci/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_nas_luci
Downloading https://istore.linkease.com/repo/all/store/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_store
Downloading https://istore.linkease.com/repo/x86_64/nas/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_nas
Downloading https://istore.linkease.com/repo/all/compat/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/istore_compat
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/targets/x86/64/packages/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_core
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/base/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_base
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/luci/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_luci
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/packages/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_packages
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/routing/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_routing
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/openwrt_telephony
Downloading https://istore.linkease.com/repo/all/meta/Packages.gz
Updated list of available packages in /tmp/is-root//tmp/opkg-lists/is_meta
Already the latest version!
Package app-meta-poweroff (1.0.0-1) installed in root is up to date.
Package app-meta-ddnsto (3.0.4-1) installed in root is up to date.
Package app-meta-systools (1.0.4-20230718) installed in root is up to date.
Package app-meta-autotimeset (1.5-20220426) installed in root is up to date.

************正在下载三大插件*******************************

--2023-09-02 13:54:08--  https://raw.github.com/AUK9527/Are-u-ok/main/x86/all/OpenClash_x86_update.run
Resolving raw.github.com... 198.18.5.50
Connecting to raw.github.com|198.18.5.50|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/AUK9527/Are-u-ok/main/x86/all/OpenClash_x86_update.run [following]
--2023-09-02 13:54:09--  https://raw.githubusercontent.com/AUK9527/Are-u-ok/main/x86/all/OpenClash_x86_update.run
Resolving raw.githubusercontent.com... 198.18.3.149
Connecting to raw.githubusercontent.com|198.18.3.149|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6716862 (6.4M) [application/octet-stream]
Saving to: 'OpenClash_x86_update.run'

OpenClash_x86_update.run      100%[===============================================>]   6.41M   135KB/s    in 37s     

2023-09-02 13:54:46 (175 KB/s) - 'OpenClash_x86_update.run' saved [6716862/6716862]

--2023-09-02 13:54:46--  https://raw.github.com/AUK9527/Are-u-ok/main/x86/all/PassWall_x86_update.run
Resolving raw.github.com... 198.18.5.50
Connecting to raw.github.com|198.18.5.50|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/AUK9527/Are-u-ok/main/x86/all/PassWall_x86_update.run [following]
--2023-09-02 13:54:48--  https://raw.githubusercontent.com/AUK9527/Are-u-ok/main/x86/all/PassWall_x86_update.run
Resolving raw.githubusercontent.com... 198.18.3.149
Connecting to raw.githubusercontent.com|198.18.3.149|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15192679 (14M) [application/octet-stream]
Saving to: 'PassWall_x86_update.run'

PassWall_x86_update.run       100%[===============================================>]  14.49M   194KB/s    in 62s     

2023-09-02 13:55:51 (238 KB/s) - 'PassWall_x86_update.run' saved [15192679/15192679]

--2023-09-02 13:55:51--  https://raw.github.com/AUK9527/Are-u-ok/main/x86/all/SSR-Plus_x86_update.run
Resolving raw.github.com... 198.18.5.50
Connecting to raw.github.com|198.18.5.50|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/AUK9527/Are-u-ok/main/x86/all/SSR-Plus_x86_update.run [following]
--2023-09-02 13:55:54--  https://raw.githubusercontent.com/AUK9527/Are-u-ok/main/x86/all/SSR-Plus_x86_update.run
Resolving raw.githubusercontent.com... 198.18.3.149
Connecting to raw.githubusercontent.com|198.18.3.149|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13327835 (13M) [application/octet-stream]
Saving to: 'SSR-Plus_x86_update.run'

SSR-Plus_x86_update.run       100%[===============================================>]  12.71M   278KB/s    in 57s     

2023-09-02 13:56:52 (228 KB/s) - 'SSR-Plus_x86_update.run' saved [13327835/13327835]

***********正在安装三大插件*********************************

Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing OneClick install  100%  
Downloading https://istore.linkease.com/repo/all/compat/Packages.gz
Updated list of available packages in /var/opkg-lists/istore_compat
Downloading https://istore.linkease.com/repo/all/compat/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/targets/x86/64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/targets/x86/64/packages/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/base/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/luci/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/packages/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/routing/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/telephony/Packages.sig
Signature check passed.
Package libcap-bin (2.63-1) installed in root is up to date.
Package libcap (2.63-1) installed in root is up to date.
Package libdb47 (4.7.25.4.NC-7) installed in root is up to date.
Package libruby3.0 (3.0.3-2) installed in root is up to date.
Package libxml2 (2.9.12-1) installed in root is up to date.
Package libyaml (0.2.5-1) installed in root is up to date.
Not downgrading package luci-app-openclash on root from 0.45.141-beta to 0.45.128-beta.
Package ruby-bigdecimal (3.0.3-2) installed in root is up to date.
Package ruby-date (3.0.3-2) installed in root is up to date.
Package ruby-dbm (3.0.3-2) installed in root is up to date.
Package ruby-digest (3.0.3-2) installed in root is up to date.
Package ruby-enc (3.0.3-2) installed in root is up to date.
Package ruby-forwardable (3.0.3-2) installed in root is up to date.
Package ruby-pstore (3.0.3-2) installed in root is up to date.
Package ruby-psych (3.0.3-2) installed in root is up to date.
Package ruby-stringio (3.0.3-2) installed in root is up to date.
Package ruby-strscan (3.0.3-2) installed in root is up to date.
Package ruby-yaml (3.0.3-2) installed in root is up to date.
Package ruby (3.0.3-2) installed in root is up to date.
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing OneClick install  100%  
Downloading https://istore.linkease.com/repo/all/compat/Packages.gz
Updated list of available packages in /var/opkg-lists/istore_compat
Downloading https://istore.linkease.com/repo/all/compat/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/targets/x86/64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/targets/x86/64/packages/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/base/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/luci/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/packages/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/routing/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/telephony/Packages.sig
Signature check passed.
Package chinadns-ng (2023.05.08-1) installed in root is up to date.
Package dns2socks (2.1-2) installed in root is up to date.
Package dns2tcp (1.1.0-1) installed in root is up to date.
Package haproxy (2.6.6-1) installed in root is up to date.
Package ipt2socks (1.1.3-2) installed in root is up to date.
Package libltdl7 (2.4.6-2) installed in root is up to date.
Package liblua5.3-5.3 (5.3.5-4) installed in root is up to date.
Package libudns (0.4-1) installed in root is up to date.
Package luci-app-passwall (4.66-8) installed in root is up to date.
Package luci-i18n-passwall-zh-cn (4.66-8) installed in root is up to date.
Package microsocks (1.0.3-1) installed in root is up to date.
Package naiveproxy (113.0.5672.62-1-1) installed in root is up to date.
Package pdnsd-alt (1.2.9b-par-3) installed in root is up to date.
Not downgrading package shadowsocks-libev-ss-local on root from 3.3.5-8 to 3.3.5-1.
Not downgrading package shadowsocks-libev-ss-redir on root from 3.3.5-8 to 3.3.5-1.
Package shadowsocks-libev-ss-server (3.3.5-1) installed in root is up to date.
Package shadowsocksr-libev-ssr-check (2.5.6-9) installed in root is up to date.
Package shadowsocksr-libev-ssr-local (2.5.6-9) installed in root is up to date.
Package shadowsocksr-libev-ssr-redir (2.5.6-9) installed in root is up to date.
Package shadowsocksr-libev-ssr-server (2.5.6-9) installed in root is up to date.
Package simple-obfs (0.0.5-1) installed in root is up to date.
Package tcping (0.3-1) installed in root is up to date.
Package unzip (6.0-8) installed in root is up to date.
Package xray-core (1.8.3-1) installed in root is up to date.
Package shadowsocks-libev-ss-local (3.3.5-8) installed in root is up to date.
Package shadowsocks-libev-ss-redir (3.3.5-8) installed in root is up to date.
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing OneClick install  100%  
Downloading https://istore.linkease.com/repo/all/compat/Packages.gz
Updated list of available packages in /var/opkg-lists/istore_compat
Downloading https://istore.linkease.com/repo/all/compat/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/targets/x86/64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/targets/x86/64/packages/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/base/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/luci/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/packages/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/routing/Packages.sig
Signature check passed.
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/22.03.4/packages/x86_64/telephony/Packages.sig
Signature check passed.
Package chinadns-ng (2023.05.08-1) installed in root is up to date.
Package dns2socks (2.1-2) installed in root is up to date.
Package dns2tcp (1.1.0-1) installed in root is up to date.
Package ipt2socks (1.1.3-2) installed in root is up to date.
Package libudns (0.4-1) installed in root is up to date.
Package lua-neturl (1.1-1-3) installed in root is up to date.
Package luci-app-ssr-plus (187-1) installed in root is up to date.
Package luci-i18n-ssr-plus-zh-cn (187-1) installed in root is up to date.
Package microsocks (1.0.3-1) installed in root is up to date.
Package naiveproxy (113.0.5672.62-1-1) installed in root is up to date.
Package pdnsd-alt (1.2.9b-par-3) installed in root is up to date.
Package redsocks2 (0.67-4) installed in root is up to date.
Not downgrading package shadowsocks-libev-ss-local on root from 3.3.5-8 to 3.3.5-1.
Not downgrading package shadowsocks-libev-ss-redir on root from 3.3.5-8 to 3.3.5-1.
Package shadowsocks-libev-ss-server (3.3.5-1) installed in root is up to date.
Package shadowsocksr-libev-ssr-check (2.5.6-9) installed in root is up to date.
Package shadowsocksr-libev-ssr-local (2.5.6-9) installed in root is up to date.
Package shadowsocksr-libev-ssr-redir (2.5.6-9) installed in root is up to date.
Package shadowsocksr-libev-ssr-server (2.5.6-9) installed in root is up to date.
Package simple-obfs (0.0.5-1) installed in root is up to date.
Package tcping (0.3-1) installed in root is up to date.
Package xray-core (1.8.3-1) installed in root is up to date.
Package shadowsocks-libev-ss-local (3.3.5-8) installed in root is up to date.
Package shadowsocks-libev-ss-redir (3.3.5-8) installed in root is up to date.

**************为emotn store添加强制域名代理********************

keeflys.com  已添加到passwall代理域名
keeflys.com  已添加到SSRP强制域名代理

***********正在安装clash dev内核*********************************

--2023-09-02 13:57:15--  https://raw.github.com/vernesong/OpenClash/core/master/dev/clash-linux-amd64.tar.gz
Resolving raw.github.com... 198.18.5.50
Connecting to raw.github.com|198.18.5.50|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/vernesong/OpenClash/core/master/dev/clash-linux-amd64.tar.gz [following]
--2023-09-02 13:57:17--  https://raw.githubusercontent.com/vernesong/OpenClash/core/master/dev/clash-linux-amd64.tar.gz
Resolving raw.githubusercontent.com... 198.18.3.149
Connecting to raw.githubusercontent.com|198.18.3.149|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2920556 (2.8M) [application/octet-stream]
Saving to: 'clashdev.tar.gz'

clashdev.tar.gz               100%[===============================================>]   2.79M   230KB/s    in 13s     

2023-09-02 13:57:30 (220 KB/s) - 'clashdev.tar.gz' saved [2920556/2920556]

clash

tun内核的更新日期是：2023.08.17

***********正在安装clash tun内核*********************************

--2023-09-02 13:57:30--  https://raw.github.com/vernesong/OpenClash/core/master/premium/clash-linux-amd64-2023.08.17.gz
Resolving raw.github.com... 198.18.5.50
Connecting to raw.github.com|198.18.5.50|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/vernesong/OpenClash/core/master/premium/clash-linux-amd64-2023.08.17.gz [following]
--2023-09-02 13:57:32--  https://raw.githubusercontent.com/vernesong/OpenClash/core/master/premium/clash-linux-amd64-2023.08.17.gz
Resolving raw.githubusercontent.com... 198.18.3.149
Connecting to raw.githubusercontent.com|198.18.3.149|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5601429 (5.3M) [application/octet-stream]
Saving to: 'clashtun.gz'

clashtun.gz                   100%[===============================================>]   5.34M   274KB/s    in 18s     

2023-09-02 13:57:50 (309 KB/s) - 'clashtun.gz' saved [5601429/5601429]

***********正在安装clash meta内核*********************************

--2023-09-02 13:57:52--  https://raw.github.com/vernesong/OpenClash/core/master/meta/clash-linux-amd64.tar.gz
Resolving raw.github.com... 198.18.5.50
Connecting to raw.github.com|198.18.5.50|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/vernesong/OpenClash/core/master/meta/clash-linux-amd64.tar.gz [following]
--2023-09-02 13:57:53--  https://raw.githubusercontent.com/vernesong/OpenClash/core/master/meta/clash-linux-amd64.tar.gz
Resolving raw.githubusercontent.com... 198.18.3.149
Connecting to raw.githubusercontent.com|198.18.3.149|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7782206 (7.4M) [application/octet-stream]
Saving to: 'clashmeta.tar.gz'

clashmeta.tar.gz              100%[===============================================>]   7.42M   174KB/s    in 33s     

2023-09-02 13:58:27 (231 KB/s) - 'clashmeta.tar.gz' saved [7782206/7782206]

clash
***********正在升级Openclash客户端到最新版*************************

OpenClash 发现新版本 : 0.45.141-beta

--2023-09-02 13:58:30--  https://raw.github.com/vernesong/OpenClash/package/master/luci-app-openclash_0.45.141-beta_all.ipk
Resolving raw.github.com... 198.18.5.50
Connecting to raw.github.com|198.18.5.50|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/vernesong/OpenClash/package/master/luci-app-openclash_0.45.141-beta_all.ipk [following]
--2023-09-02 13:58:31--  https://raw.githubusercontent.com/vernesong/OpenClash/package/master/luci-app-openclash_0.45.141-beta_all.ipk
Resolving raw.githubusercontent.com... 198.18.3.149
Connecting to raw.githubusercontent.com|198.18.3.149|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4354447 (4.2M) [application/octet-stream]
Saving to: 'newopenclash.ipk'

newopenclash.ipk              100%[===============================================>]   4.15M   269KB/s    in 14s     

2023-09-02 13:58:45 (299 KB/s) - 'newopenclash.ipk' saved [4354447/4354447]

Package luci-app-openclash (0.45.141-beta) installed in root is up to date.

******************大功告成! 悟空all in one一键脚本全部安装完毕 *******************

**Comment by wukongdaily** [comment]
你好 ，日志看起来是正确的日志。建议断电重启一下j1900 试试？

**Comment by BGMISBPT** [comment]
多谢你看到回复这个问题，设备已经断电重启，重启后重新进入iStoreOS，发现服务选项下只有OpenClash，没有其他科学插件。

**Comment by wukongdaily** [comment]
嗯嗯，新版passwall 和 ssrp位于VPN菜单底下。不是在 “服务”底下哦

**Comment by BGMISBPT** [comment]
好的，在VPN菜单下已经看到了，多谢你一键安装脚本。
