### ISSUE TITLE
安装问题请教

### ISSUE THREAD

**Issue by monstertmh** [wukongdaily/allinonescript#3]
您好，r5s用arm版本离线包安装，安装到结尾卡住了，页面手动刷新后看到了三大软件，安装日志最后部分如下，请问是否已安装完整呢？

***********正在升级Openclash客户端到最新版*************************

--2023-09-04 14:20:52--  https://raw.githubusercontent.com/vernesong/OpenClash/package/master/luci-app-openclash_0.45.141-beta_all.ipk
Resolving raw.githubusercontent.com... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4354447 (4.2M) [application/octet-stream]
Saving to: 'newopenclash.ipk'

newopenclash.ipk    100%[===================>]   4.15M  2.24MB/s    in 1.9s    

2023-09-04 14:20:55 (2.24 MB/s) - 'newopenclash.ipk' saved [4354447/4354447]

Upgrading luci-app-openclash on root from 0.45.128-beta to 0.45.141-beta...
OpenClash Already Stop!
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Logs-ad267e02.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Connections-2c1d9d67.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/index-8c12d331.css.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/index.esm-37f2c08f.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/TextFitler-4f121c73.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Rules-6bba7454.js.
Removing obsolete file /usr/share/openclash/ui/dashboard/workbox-e0782b83.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/inter-latin-800-normal-d08d7178.woff.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/logs-08774dd8.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/index-3e6aad90.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/inter-latin-400-normal-3ea830d4.woff.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/play-30aef65c.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/roboto-mono-latin-400-normal-dffdffa7.woff.
Removing obsolete file /usr/share/openclash/ui/dashboard/assets/index-9ebfe719.css.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/chart-lib-ced68107.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/chevron-down-fcc32a65.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Select-1e55eba1.css.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/index-534e085e.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/TextFitler-b21c0577.css.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Config-b8a90983.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/useRemainingViewPortHeight-175c2a6c.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Fab-169bb281.js.
Removing obsolete file /usr/share/openclash/ui/dashboard/assets/index-a1967476.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Select-4fa356cc.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/index-2a3ca6b4.js.
Removing obsolete file /usr/share/openclash/ui/yacd/assets/Proxies-869a8128.js.
Removing obsolete file /usr/share/openclash/ui/dashboard/assets/vendor-0606363c.js.
Configuring luci-app-openclash.
cfg227882

**Comment by wukongdaily** [comment]
你好，看日志算正常，你可以重启一下路由器或者退出webui在进来。试试看。另外建议运行一下，我制作的 带菜单版本的命令行。那个可以单独安装openclash。这些命令都可以反复执行的。
