### ISSUE TITLE
感觉是不是带菜单版一键脚本(集合全部功能)失效了

### ISSUE THREAD

**Issue by snake94115** [wukongdaily/allinonescript#4]
-------------------------------------------------------
 iStoreOS 22.03.5, 2023090112
 -------------------------------------------------------
root@iStoreOS:~# wget -O /tmp/allmenu.run  https://raw.githubusercontent.com/wukongdaily/allinonescript/main/all/allmenu.run && chmod +x /tmp/allmenu.run  && /tmp/allmenu.run
--2023-09-07 10:40:58--  https://raw.githubusercontent.com/wukongdaily/allinonescript/main/all/allmenu.run
Resolving raw.githubusercontent.com... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 50006 (49K) [application/octet-stream]
Saving to: '/tmp/allmenu.run'

/tmp/allmenu.run                                    100%[================================================================================================================>]  48.83K  --.-KB/s    in 0.07s   

2023-09-07 10:40:58 (717 KB/s) - '/tmp/allmenu.run' saved [50006/50006]

-ash: /tmp/allmenu.run: Text file busy
root@iStoreOS:~#

**Comment by wukongdaily** [comment]
你好 日志上来看，似乎文件已经成功下载到/tmp/allmenu.run ，执行的时候好像出问题 ，你是什么机型呢

**Comment by snake94115** [comment]
i7的1165G7，6网口，esxi下安装的itsoreos试了几遍现在又好使了

**Comment by wukongdaily** [comment]
好的，那就好。

**Comment by wukongdaily** [comment]
那就关闭了
